### ISSUE TITLE
Will you support swift2.0?

### ISSUE THREAD

**Issue by pine** [mihyaeru21/Aurum#6]
I want to compile Swift more speedy than Swift 1.x !!

**Comment by mattak** [comment]
:+1: :+1:

**Comment by pine** [comment]
:+1:

**Comment by pine** [comment]
Travis CI is ready. :smile: 
http://blog.travis-ci.com/2015-08-26-xcode-70-beta-is-now-available/

**Comment by mattak** [comment]
:+1:

**Comment by mattak** [comment]
:+1: :+1: :+1:

**Comment by mihyaeru21** [comment]
:+1:  https://github.com/mihyaeru21/Aurum/tree/swift-2.0
